### ISSUE TITLE
Base bump for ghc-8.10

### ISSUE THREAD

**Issue by neurogoo** [futurice/haskell-ansi-pretty#20]
Hi. For ghc-8.10 there needs to be bump for base library to get this library compile. Also, I noticed that the .cabal file still has old url's. I made the necessary changes here https://github.com/neurogoo/ansi-pretty/tree/ghc-8.10 but didn't make PR as base bump by itself doesn't need any source code changes

**Comment by phadej** [comment]
Revision made https://hackage.haskell.org/package/ansi-pretty-0.1.2.2/revisions/
